export const TID = {
  ageGate: {
    dialog: "age-gate-dialog",
    confirm: "age-gate-confirm-button",
    reject: "age-gate-reject-button",
  },
  nav: {
    logo: "nav-logo",
    ask: "nav-ask-ai",
    mens: "nav-mens-health",
    womens: "nav-womens-health",
    sti: "nav-sti",
    contra: "nav-contraception",
    wellness: "nav-wellness",
    relationships: "nav-relationships",
    imageCheck: "nav-image-check",
    privacy: "nav-privacy",
    mobileToggle: "nav-mobile-toggle",
  },
  home: {
    heroTitle: "home-hero-title",
    chatInput: "home-chat-input",
    chatSend: "home-chat-send",
    examplePrompt: (i) => `home-example-prompt-${i}`,
    hub: (slug) => `home-hub-${slug}`,
    imageCheckCta: "home-image-check-cta",
  },
  chat: {
    input: "chat-input",
    send: "chat-send",
    message: (i) => `chat-message-${i}`,
    disclaimer: "chat-disclaimer",
  },
  symptom: {
    symptom: "symptom-input",
    area: "symptom-body-area",
    duration: "symptom-duration",
    severity: "symptom-severity",
    associated: "symptom-associated",
    context: "symptom-context",
    submit: "symptom-submit",
    result: "symptom-result",
  },
  imageCheck: {
    fileInput: "image-check-file-input",
    fileDrop: "image-check-drop-zone",
    payBtn: "image-check-pay-button",
    result: "image-check-result",
    deleteBtn: "image-check-delete-image",
    note: "image-check-note",
  },
  admin: {
    email: "admin-email",
    password: "admin-password",
    submit: "admin-login-submit",
    logout: "admin-logout",
    statsPanel: "admin-stats-panel",
  },
};
